### ISSUE TITLE
Our own version number: string or unicode or bytes

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/zest.releaser#110]
When I do a prerelease on our own master, pyroma complains: The version number should be a string. This is because at the top of setup.py we import unicode_literals.

I can change it to `version = b'5.1.dev0'` and then pyroma is happy. But prerelease cannot write it back:

```
RROR: We could read a version from setup.py, but could not write it back. See http://zestreleaser.readthedocs.org/en/latest/versions.html for hints.
Traceback (most recent call last):
  File "/Users/mauritsvanrees/buildout/tools/bin/prerelease", line 39, in <module>
    sys.exit(zest.releaser.prerelease.main())
  File "/Users/mauritsvanrees/buildout/tools/src/zest.releaser/zest/releaser/prerelease.py", line 193, in main
    prereleaser.run()
  File "/Users/mauritsvanrees/buildout/tools/src/zest.releaser/zest/releaser/baserelease.py", line 36, in run
    self.execute()
  File "/Users/mauritsvanrees/buildout/tools/src/zest.releaser/zest/releaser/prerelease.py", line 70, in execute
    self._write_version()
  File "/Users/mauritsvanrees/buildout/tools/src/zest.releaser/zest/releaser/prerelease.py", line 91, in _write_version
    self.vcs.version = self.data['new_version']
  File "/Users/mauritsvanrees/buildout/tools/src/zest.releaser/zest/releaser/vcs.py", line 244, in _update_version
    raise RuntimeError("Cannot set version")
RuntimeError: Cannot set version
```

Maybe pyroma should just not complain. I don't know yet.

**Comment by reinout** [comment]
I think it is pyroma that should stop complaining.

**Comment by mauritsvanrees** [comment]
Actually, a pyroma on Python 2.7 complains, but on Python 3 not. :-) So looks like we are fine. I have created a pull request on pyroma for this: https://bitbucket.org/regebro/pyroma/pull-request/9

**Comment by reinout** [comment]
Nice!

Once a new pyroma release is out, perhaps add a note in *our* changelog anyway?

**Comment by mauritsvanrees** [comment]
Lennard has merged my pyroma pull request.

Not sure what to write in our changelog. Anything I write would seem like a message for a *really* small target reader group that happens to run into this same problem because they are straddling Python 2 and 3 in a package and use unicode literals and a soon to be replaced version of pyroma.

**Comment by reinout** [comment]
Agreed.
