### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in HISTORY.txt

### ISSUE THREAD

**Issue by allcaps** [zestsoftware/zest.releaser#118]
When I add the text '- Have a ☃ (snowman).' to my history file, and run `fullrelease`, then `prerelease` gets called and gives a UnicodeEncodeError:

Traceback (most recent call last):
  File "/Users/coen/bin/fullrelease", line 38, in <module>
    sys.exit(zest.releaser.fullrelease.main())
  File "/Users/coen/.buildout/shared-eggs/zest.releaser-5.0-py2.7.egg/zest/releaser/fullrelease.py", line 21, in main
    prerelease.main()
  File "/Users/coen/.buildout/shared-eggs/zest.releaser-5.0-py2.7.egg/zest/releaser/prerelease.py", line 193, in main
    prereleaser.run()
  File "/Users/coen/.buildout/shared-eggs/zest.releaser-5.0-py2.7.egg/zest/releaser/baserelease.py", line 36, in run
    self.execute()
  File "/Users/coen/.buildout/shared-eggs/zest.releaser-5.0-py2.7.egg/zest/releaser/prerelease.py", line 71, in execute
    self._write_history()
  File "/Users/coen/.buildout/shared-eggs/zest.releaser-5.0-py2.7.egg/zest/releaser/prerelease.py", line 161, in _write_history
    open(history, 'w').write(contents)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 102-104: ordinal not in range(128)

**Comment by mauritsvanrees** [comment]
This was fixed in zest.releaser 5.1. (Note: I have just now updated our internal tools buildout to use that version.)

Note: when running prerelease the text may be changed into `Have a â (snowman)` instead, which it seems cannot really be helped.
