### ISSUE TITLE
Switch from z3c.testsetup to nose (or unittest2)

### ISSUE THREAD

**Issue by reinout** [zestsoftware/zest.releaser#12]
Nose or unittest2 mean a more familiar test setup for many people. And it'll cut down on the number of dependencies we pull in for testing :-)

**Comment by graingert** [comment]
`py.test` is generally more popular.

**Comment by reinout** [comment]
nose and py.test are pretty much equivalent in popularity, I believe. (And I'm familiar with nose myself... :-) )

**Comment by mauritsvanrees** [comment]
We need to switch away from `z3c.testsetup` if we want to support Python 3.11. When I try it, I get an ImportError:

```
py311 run-test: commands[0] | zope-testrunner --test-path=. '--tests-pattern=^tests$' -v -c
Test-module import failures:

Module: zest.releaser.tests.test_setup

Traceback (most recent call last):
  File "/Users/maurits/community/zest.releaser/zest/releaser/tests/test_setup.py", line 7, in <module>
    import z3c.testsetup
  File "/Users/maurits/community/zest.releaser/.tox/py311/lib/python3.11/site-packages/z3c/testsetup/__init__.py", line 1, in <module>
    from z3c.testsetup.doctesting import UnitDocTestSetup
  File "/Users/maurits/community/zest.releaser/.tox/py311/lib/python3.11/site-packages/z3c/testsetup/doctesting.py", line 22, in <module>
    from z3c.testsetup.base import BasicTestSetup
  File "/Users/maurits/community/zest.releaser/.tox/py311/lib/python3.11/site-packages/z3c/testsetup/base.py", line 21, in <module>
    from z3c.testsetup.util import get_package
  File "/Users/maurits/community/zest.releaser/.tox/py311/lib/python3.11/site-packages/z3c/testsetup/util.py", line 22, in <module>
    from inspect import getmro, ismethod, isfunction, getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/Users/maurits/.pyenv/versions/3.11.0/lib/python3.11/inspect.py)
```

I am trying out how hard it is to get rid of it. It is only about test discovery and setup/teardown, not about which test running. So we should be able to stay with `zope.testrunner`, although this is up for replacement by pytest, which is more popular than nose these days as far as I know.
