### ISSUE TITLE
Error registring with twine

### ISSUE THREAD

**Issue by gforcada** [zestsoftware/zest.releaser#147]
I just released [freitag.releaser](https://pypi.python.org/pypi/freitag.releaser) and I had to do it twice because the first time it errored while registering it on PyPI.

After manually trying to register the package (``python setup.py register``) I was told that there was an error on the trove classifiers (fixed https://github.com/derFreitag/freitag.releaser/commit/77d735485f18c692534189f75b72a10b731f0fa0).

Should I file a bug against twine?

**Comment by reinout** [comment]
I'm not sure. Do you still have access to the screen output you saw? I wonder what the error message (if any) was.

It might be a bug in twine, it might be an unclear error message in twine.

It might just as well be that twine reports the error, but that zest.releaser suppresses it in some way.

Did you try running twine by hand?

**Comment by gforcada** [comment]
No, I did not try running twine by hand unfortunately. I have the traceback though:

This is the error when trying to register
```
Register and upload to pypi (y/N)? yes
INFO: Registering...
Registering package to https://pypi.python.org/pypi
Registering freitag.releaser-0.2.tar.gz
INFO: Starting new HTTPS connection (1): pypi.python.org
There were errors or warnings.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file utils.py, line 685
```

And when quitting I also get this traceback:
```
Retry this command? [Yes/no/quit/?]quit
Traceback (most recent call last):
  File "./bin/fullrelease", line 71, in <module>
    sys.exit(zest.releaser.fullrelease.main())
  File "/home/gil/.buildout/eggs/zest.releaser-6.2-py2.7.egg/zest/releaser/fullrelease.py", line 27, in main
    releaser.run()
  File "/home/gil/.buildout/eggs/zest.releaser-6.2-py2.7.egg/zest/releaser/baserelease.py", line 42, in run
    self.execute()
  File "/home/gil/.buildout/eggs/zest.releaser-6.2-py2.7.egg/zest/releaser/release.py", line 65, in execute
    self._release()
  File "/home/gil/.buildout/eggs/zest.releaser-6.2-py2.7.egg/zest/releaser/release.py", line 253, in _release
    self._upload_distributions(package)
  File "/home/gil/.buildout/eggs/zest.releaser-6.2-py2.7.egg/zest/releaser/release.py", line 171, in _upload_distributions
    utils.retry_twine('register', server, files_in_dist)
  File "/home/gil/.buildout/eggs/zest.releaser-6.2-py2.7.egg/zest/releaser/utils.py", line 689, in retry_twine
    return retry_twine(twine_command, server, *files)
  File "/home/gil/.buildout/eggs/zest.releaser-6.2-py2.7.egg/zest/releaser/utils.py", line 686, in retry_twine
    retry = retry_yes_no('twine %s' % twine_command)
  File "/home/gil/.buildout/eggs/zest.releaser-6.2-py2.7.egg/zest/releaser/utils.py", line 725, in retry_yes_no
    raise CommandException("Command failed: %r" % command)
zest.releaser.utils.CommandException: Command failed: u'twine register'
```

**Comment by reinout** [comment]
I was looking at the logging line in our code and couldn't find an error. But... :-) Maurits fixed something in that logging routine on 31 october.

@mauritsvanrees: we should probably release it, right?

**Comment by reinout** [comment]
So: zest.releaser has a bug that suppresses the error message. Well, actually, it suppresses printing the traceback emitted by twine.

Maurits' fix make sure the traceback is printed now.

**Comment by mauritsvanrees** [comment]
Hm, now why didn't I release that yet??? Done now: 6.3.

Note that the fix is in 7d9245345f003d91efb1c9613a02fdaff9fff309

**Comment by reinout** [comment]
:-)

**Comment by gforcada** [comment]
Thanks!
