### ISSUE TITLE
Error on retrying "twine upload"

### ISSUE THREAD

**Issue by gforcada** [zestsoftware/zest.releaser#148]
While trying to upload freitag.releaser 0.5 I got a 500 from PyPI and then freitag.releaser broke:

```
Upload to pypi (Y/n)? 
Uploading distributions to https://pypi.python.org/pypi
Uploading freitag.releaser-0.5.tar.gz
INFO: Starting new HTTPS connection (1): pypi.python.org



There were errors or warnings.
ERROR: Package upload has failed.
Traceback (most recent call last):
  File "/home/gil/.buildout/eggs/zest.releaser-6.3-py2.7.egg/zest/releaser/utils.py", line 682, in retry_twine
    return twine_function(*twine_args)
  File "/home/gil/.buildout/eggs/twine-1.6.1-py2.7.egg/twine/commands/upload.py", line 126, in upload
    resp.raise_for_status()
  File "/home/gil/.buildout/eggs/requests-2.7.0-py2.7.egg/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error
Retry this command? [Yes/no/quit/?]INFO: Retrying command: u'twine upload'
INFO: Retrying.
Uploading distributions to https://pypi.python.org/pypi
There were errors or warnings.
ERROR: Package upload has failed.
Traceback (most recent call last):
  File "/home/gil/.buildout/eggs/zest.releaser-6.3-py2.7.egg/zest/releaser/utils.py", line 682, in retry_twine
    return twine_function(*twine_args)
  File "/home/gil/.buildout/eggs/twine-1.6.1-py2.7.egg/twine/commands/upload.py", line 89, in upload
    uploads = find_dists(dists)
  File "/home/gil/.buildout/eggs/twine-1.6.1-py2.7.egg/twine/commands/upload.py", line 49, in find_dists
    "Cannot find file (or expand pattern): '%s'" % filename
ValueError: Cannot find file (or expand pattern): 'd'
Retry this command? [Yes/no/quit/?]INFO: Retrying command: u'twine upload'
INFO: Retrying.
Traceback (most recent call last):
  File "./bin/fullrelease", line 71, in <module>
    sys.exit(zest.releaser.fullrelease.main())
  File "/home/gil/.buildout/eggs/zest.releaser-6.3-py2.7.egg/zest/releaser/fullrelease.py", line 27, in main
    releaser.run()
  File "/home/gil/.buildout/eggs/zest.releaser-6.3-py2.7.egg/zest/releaser/baserelease.py", line 42, in run
    self.execute()
  File "/home/gil/.buildout/eggs/zest.releaser-6.3-py2.7.egg/zest/releaser/release.py", line 65, in execute
    self._release()
  File "/home/gil/.buildout/eggs/zest.releaser-6.3-py2.7.egg/zest/releaser/release.py", line 253, in _release
    self._upload_distributions(package)
  File "/home/gil/.buildout/eggs/zest.releaser-6.3-py2.7.egg/zest/releaser/release.py", line 172, in _upload_distributions
    utils.retry_twine('upload', server, files_in_dist)
  File "/home/gil/.buildout/eggs/zest.releaser-6.3-py2.7.egg/zest/releaser/utils.py", line 689, in retry_twine
    return retry_twine(twine_command, server, *files)
  File "/home/gil/.buildout/eggs/zest.releaser-6.3-py2.7.egg/zest/releaser/utils.py", line 689, in retry_twine
    return retry_twine(twine_command, server, *files)
TypeError: retry_twine() takes exactly 3 arguments (34 given)
```

Interestingly enough, on the output above there are two times where I was asked to retry, which I'm totally unaware of having answered it at all...

**Comment by mauritsvanrees** [comment]
Confirmed, when I try this with a test package and upload it to testpypi with a wrong password in my pypirc, I get the same. Probably a string gets interpreted as a list of characters. I am very sure I have seen this working. I'll check.

For not recalling having answered those questions: maybe you called it with `--no-input` or have that option in your setup.cfg or pypirc. Or earlier in the process you have pressed Enter too often.

**Comment by mauritsvanrees** [comment]
I have released 6.4 with a fix.

**Comment by gotcha** [comment]
May I suggest using semantic versioning for zest.releaser ?
In my opinion, 6.1 could have been 6.0.1
Then 6.2 could have been 6.1 and 6.3 and 6.4, 6.1.1 and 6.1.2 respectively.

**Comment by reinout** [comment]
Well, with real semantic versioning every backwards incompatibility or change in a config file needs a major version number increase. We'd have been at 24.0.1 now :-)

But I agree that 6.4 should/could have been 6.3.1, it is really a bugfix release for 6.3. We're probably too free with the major.minor releases :-)

**Comment by gotcha** [comment]
I like 24.0.1 :)

**Comment by gforcada** [comment]
@mauritsvanrees as usual, thanks a lot!
