### ISSUE TITLE
URLError when trying to make a release

### ISSUE THREAD

**Issue by hvelarde** [zestsoftware/zest.releaser#181]
I'm getting the following error when trying to do a release using zest.releaser v6.6.4:

```python
Traceback (most recent call last):
  File "/home/hvelarde/collective/releaser/bin/release", line 11, in <module>
    sys.exit(main())
  File "/home/hvelarde/collective/releaser/lib/python2.7/site-packages/zest/releaser/release.py", line 260, in main
    releaser.run()
  File "/home/hvelarde/collective/releaser/lib/python2.7/site-packages/zest/releaser/baserelease.py", line 308, in run
    self.execute()
  File "/home/hvelarde/collective/releaser/lib/python2.7/site-packages/zest/releaser/release.py", line 65, in execute
    self._release()
  File "/home/hvelarde/collective/releaser/lib/python2.7/site-packages/zest/releaser/release.py", line 245, in _release
    self._upload_distributions(package)
  File "/home/hvelarde/collective/releaser/lib/python2.7/site-packages/zest/releaser/release.py", line 128, in _upload_distributions
    on_pypi = package_in_pypi(package)
  File "/home/hvelarde/collective/releaser/lib/python2.7/site-packages/zest/releaser/release.py", line 40, in package_in_pypi
    urllib2.urlopen(url)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
```
any idea of what's going on?

**Comment by mauritsvanrees** [comment]
That is in this function:
https://github.com/zestsoftware/zest.releaser/blob/6.6.4/zest/releaser/release.py#L36
So we are using urllib to fetch `'https://pypi.python.org/simple/%s' % package`.
Do you maybe not have https/ssl support compiled into python?
Can you reach that url with wget or curl or something?

**Comment by hvelarde** [comment]
I can wget that URL; it's weird because is the same Python I was using before.

**Comment by hvelarde** [comment]
I just remembered that I upgraded the other day my OS; I will recompile my Pythons and let you know.

**Comment by hvelarde** [comment]
well, this is very weird indeed; I recompiled everything from scratch and I continue facing the same error. I even tried using requests in that part of the code with the same error:

```python
(Pdb) url
u'https://pypi.python.org/simple/collective.cover'
(Pdb) import requests
(Pdb) requests.get(url)    
INFO: Starting new HTTPS connection (1): pypi.python.org
*** ConnectionError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/collective.cover (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f41285bd890>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

as you can see here my Python has indeed support for SSL:

```python
# python
Python 2.7.12 (default, Jul  4 2016, 09:09:16) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> hasattr(socket, 'ssl')
True
```

any hint will be truly appreciated.

**Comment by hvelarde** [comment]
seems to be a DNS issue:

```console
# wget https://pypi.python.org/simple/collective.cover
--2016-07-04 10:33:28--  https://pypi.python.org/simple/collective.cover
Resolving pypi.python.org (pypi.python.org)... failed: Name or service not known.
wget: unable to resolve host address ‘pypi.python.org’

```
