### ISSUE TITLE
git diff encoding different from UTF-8

### ISSUE THREAD

**Issue by Natim** [zestsoftware/zest.releaser#210]
If you create a file in latin-1, commit it and then change its encoding in utf-8 before running prerelease for instance you will get a UnicodeDecode error.

```
Traceback (most recent call last):
  File "/usr/local/bin/prerelease", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/zest/releaser/prerelease.py", line 103, in main
    prereleaser.run()
  File "/usr/local/lib/python2.7/dist-packages/zest/releaser/baserelease.py", line 353, in run
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/zest/releaser/prerelease.py", line 69, in execute
    self._diff_and_commit()
  File "/usr/local/lib/python2.7/dist-packages/zest/releaser/baserelease.py", line 316, in _diff_and_commit
    diff = execute_command(diff_cmd)
  File "/usr/local/lib/python2.7/dist-packages/zest/releaser/utils.py", line 771, in execute_command
    result = _execute_command(command)
  File "/usr/local/lib/python2.7/dist-packages/zest/releaser/utils.py", line 698, in _execute_command
    stdout_output = stdout_output.decode(OUTPUT_ENCODING)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 4197: invalid start byte
```

I guess it is a edge case of me using prerelease before having commited this change but I guess that's something we could prevent.

**Comment by mauritsvanrees** [comment]
If this is still a problem, please try with latest version [7.0.0a1](https://pypi.org/project/zest.releaser/7.0.0a1/). Python 3 only, so maybe encoding problems have gone away.
