### ISSUE TITLE
date-format syntax in setup.cfg breaks pip

### ISSUE THREAD

**Issue by mgedmin** [zestsoftware/zest.releaser#226]
Unfortunately putting `date-format = %B %e, %Y` in a `setup.cfg` breaks the interpolating config parser (on Python 3) which is used, among other tools, by pip:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/travis/build/mgedmin/dozer/setup.py", line 64, in <module>
        """,
      File "/opt/python/3.6.1/lib/python3.6/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/setuptools/dist.py", line 355, in parse_config_files
        _Distribution.parse_config_files(self, filenames=filenames)
      File "/opt/python/3.6.1/lib/python3.6/distutils/dist.py", line 402, in parse_config_files
        val = parser.get(section,opt)
      File "/opt/python/3.6.1/lib/python3.6/configparser.py", line 800, in get
        d)
      File "/opt/python/3.6.1/lib/python3.6/configparser.py", line 394, in before_get
        self._interpolate_some(parser, option, L, value, section, defaults, 1)
      File "/opt/python/3.6.1/lib/python3.6/configparser.py", line 444, in _interpolate_some
        "found: %r" % (rest,))
    configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%B %e, %Y'
```

This makes it impossible to use `date-format` :/

I have a workaround in mind: allow `%%B %%e %%Y` to be interpreted the same as `%B %e %Y` with a quick `.replace('%%', '%')` before passing the date format to `strftime()`.

**Comment by mauritsvanrees** [comment]
Thanks. Your fix is included in release 6.12.1.
