### ISSUE TITLE
Need a option to sign when uploading (pass `--sign` to `twine upload`)

### ISSUE THREAD

**Issue by htgoebel** [zestsoftware/zest.releaser#238]
For PyInstaller, we are using a [`releaser.before_upload` hook](https://github.com/pyinstaller/pyinstaller/blob/develop/setup.cfg#L9) to [sign releases](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/release.py#L27).
Now twine no longer allows uploading the additional file but fail (see below) with 
```
  Unknown distribution format: 'PyInstaller-3.3.tar.gz.asc'
```
##### Proposed solution
`twine upload` has an option `sign`, so all we need is a way to pass this option to `twine upload`.

##### Traceback
```
$ release
Tag needed to proceed, you can use the following command:
git tag 3.3 -m "Tagging 3.3"
Run this command (Y/n)? 
Check out the tag (for tweaks or pypi/distutils server upload) (Y/n)? 
INFO: Doing a checkout...
…
Writing PyInstaller-3.3/setup.cfg
creating dist
Creating tar archive
removing 'PyInstaller-3.3' (and everything under it)

Signing file /tmp/PyInstaller-3.3-8mqhmxfv/gitclone/dist/PyInstaller-3.3.tar.gz

… [Enter passphrese for gpgp key]
Upload to testpypi (Y/n)?     
Traceback (most recent call last):
  File "/tmp/py-web/bin/release", line 11, in <module>
    sys.exit(main())
  File "/tmp/py-web/lib64/python3.5/site-packages/zest/releaser/release.py", line 332, in main
    releaser.run()
  File "/tmp/py-web/lib64/python3.5/site-packages/zest/releaser/baserelease.py", line 353, in run
    self.execute()
  File "/tmp/py-web/lib64/python3.5/site-packages/zest/releaser/release.py", line 71, in execute
    self._release()
  File "/tmp/py-web/lib64/python3.5/site-packages/zest/releaser/release.py", line 317, in _release
    self._upload_distributions(package)
  File "/tmp/py-web/lib64/python3.5/site-packages/zest/releaser/release.py", line 167, in _upload_distributions
    self._retry_twine('upload', server, filename)
  File "/tmp/py-web/lib64/python3.5/site-packages/zest/releaser/release.py", line 185, in _retry_twine
    package_file = PackageFile.from_filename(filename, comment=None)
  File "/tmp/py-web/lib64/python3.5/site-packages/twine/package.py", line 93, in from_filename
    os.path.basename(filename)
ValueError: Unknown distribution format: 'PyInstaller-3.3.tar.gz.asc'
```

**Comment by reinout** [comment]
Weird. If I look at the 1.9.1 twine code, the part of the code that prints out "unkown distribution format" loops over a list where `*.asc` has been filtered out!

So I assume it still ought to work. I've checked the current master (https://github.com/pypa/twine/blob/master/twine/commands/upload.py#L87) and it still looks fine, there. It should automatically pick up a `.asc` signature.

Can you debug a bit further? I've looked at passing in `sign=True` or so, but it looks like you need to pass in an identity, too, then. So it looks a bit more complex than I expected.

**Comment by htgoebel** [comment]
>So I assume it still ought to work.

I tried the latest release and it id not work. I have no time for debugging this, sorry.

**Comment by htgoebel** [comment]
Instead of spending time on debugging this, the time could be used to add the requested option and we could even drop our plugin :-)

**Comment by mauritsvanrees** [comment]
It goes wrong because zest.releaser is calling [`Packagefile.from_filename`](https://github.com/zestsoftware/zest.releaser/blob/master/zest/releaser/release.py#L186) on all files, including the `.asc` file, and that one fails.

We could filter out those `.asc` files so twine does not choke on them. And for any file that we upload, we could check if there is an accompanying `.asc` file that we pass to twine in one command.

**Comment by htgoebel** [comment]
I started implementing this and while analyzing how to implement it, I (presumably) found the root-cause of this issue:

As @mauritsvanrees  write, twine [contains code](https://github.com/pypa/twine/blob/1.9.1/twine/commands/upload.py#L83) for filtering `.asc`-files and adding them as signature for the respective file. This is done in `twine.commands.upload.upload()`. But zest.releaser is using a low-level function, `Repository.upload()`, passing [files one by one](https://github.com/zestsoftware/zest.releaser/blob/6.13.0/zest/releaser/release.py#L169). Thus the aforementioned code in `commands.upload` is not executed.

What about switching to use the high-level functions? As far as I understood releaser's code, we could even get rid of quite some code, e.g. for handling repositories, and maybe even more for reading the `.pypyprc`-file

**Comment by reinout** [comment]
Note: we use the `.pypirc` file also for some defaults. I don't think it is used very much in practice for that purpose, however.

**Comment by reinout** [comment]
Getting rid of code is always good, in principle.

Twine: we'll have to make sure the higher-level functions are actually intended to be used as an API. If I remember correctly, twine once changed its internal API, breaking zest.releaser. At that time, it wasn't intended to be used as an API yet (or we probably picked the wrong abstraction level and used functions that were too low-level).

Summary: if we're going to use twine on a different level, we'll have to talk to the twine people first :-)

**Comment by htgoebel** [comment]
It should be reasonable save to "run" the commands, e.g.
`twine.commands.upload.main("--repository", server, *files_in_dist)`.

Anyway talking to the twine people would be a good choice. Are you going to to this?

**Comment by mauritsvanrees** [comment]
Nope. We were using the `upload` and `register` functions before, but the twine people have made it abundantly clear in the past that those should not be used as an API. See https://github.com/zestsoftware/zest.releaser/pull/189

**Comment by htgoebel** [comment]
I'm not suggesting to use `upload()`, but `main()` and passing it the *command line arguments*. So it's nearly the same as running twine via `subcommand.Popen()?. ID#d expect the command-line arguments not to break without prior notice. YMMV.

**Comment by reinout** [comment]
Our mileage already did vary :-)

But it might be OK to call `main()`, though I'm not sure, seeing the discussion @mauritsvanrees had.

It sounds a bit the same as pip, that one also has no API. "The only API is the command line". So tools like buildout cannot use it except through the command line (if buildout wanted).

**Comment by mauritsvanrees** [comment]
Easiest still seems what I suggested earlier:

> We could filter out those .asc files so twine does not choke on them. And for any file that we upload, we could check if there is an accompanying .asc file that we pass to twine in one command.

That seems doable without much extra code and without a complete restructuring of how we call twine.

**Comment by htgoebel** [comment]
> We could filter out those .asc files so twine does not choke on them. And for any file that we upload, we could check if there is an accompanying .asc file that we pass to twine in one command.

I tried this and found myself re-implementing quite some parts of `twine.commands.upload#upload()`. Not only one would need to filter out the `.asc` files first, but also `add_gpg_signature` to each file to be uploaded, if the signature exists. Although this would still be only a view lines, keeping up with twine features and PyPI API changes would become a cat-and-mice-game in he long run.

I asked for another high-level api (see https://github.com/pypa/twine/issues/194), one of which `twine.cli.dispatch()` could be. This would allow something like:
```
dispatch(twine_command, '-r', server, *files_in_dist)
```

**Comment by reinout** [comment]
I think we have this fixed now in 6.18.0, right?

**Comment by htgoebel** [comment]
> I think we have this fixed now in 6.18.0, right?

I can't see how 6.18.0 solved this. Did I miss something?

**Comment by reinout** [comment]
You said this in one of the comments:

> What about switching to use the high-level functions? As far as I understood releaser's code, we could even get rid of quite some code, e.g. for handling repositories, and maybe even more for reading the `.pypyprc`-file

So I guessed that, now that we call `twine.cli.script()`, twine does all the work for us, including dealing with `.asc` files.

I thought that "just let twine do the right thing" was one of the goals of the recent change :-)
I might be mixing things up, though!

**Comment by htgoebel** [comment]
We still need to pass `--sign?` to twine. Please reopen this issue. Thanks.

**Comment by htgoebel** [comment]
PyPI no longer accepts GPG signature files: they are simply discarded — and the developer gets an e-mail about this. So this can be closed.
