### ISSUE TITLE
Support version reference in setup.cfg

### ISSUE THREAD

**Issue by Aluriak** [zestsoftware/zest.releaser#288]
This is the important part of my `setup.cfg`:

```
[metadata]
version = attr: mypackage.__version__
```

Before, i was directly putting the version number here, and it worked well with zest.releaser. However, to get a `__version__` attribute in my package, i would have to maintain it manually.
As a consequence, this writing allows me to have to write only one time the version number.

But when running zest.releaser will yield the following error:

```
[…]
Changelog entries for version 0.6.7:


Enter version [0.6.7]: 
ERROR: We could read a version from setup.py, but could not write it back. See http://zestreleaser.readthedocs.io/en/latest/versions.html for hints.
Traceback (most recent call last):
  File "/home/lbourneu/packages/bubble-tools/venv/bin/fullrelease", line 11, in <module>
    sys.exit(main())
  File "/home/lbourneu/packages/bubble-tools/venv/lib/python3.6/site-packages/zest/releaser/fullrelease.py", line 23, in main
    prereleaser.run()
  File "/home/lbourneu/packages/bubble-tools/venv/lib/python3.6/site-packages/zest/releaser/baserelease.py", line 391, in run
    self.execute()
  File "/home/lbourneu/packages/bubble-tools/venv/lib/python3.6/site-packages/zest/releaser/prerelease.py", line 74, in execute
    self._write_version()
  File "/home/lbourneu/packages/bubble-tools/venv/lib/python3.6/site-packages/zest/releaser/baserelease.py", line 320, in _write_version
    self.vcs.version = self.data['new_version']
  File "/home/lbourneu/packages/bubble-tools/venv/lib/python3.6/site-packages/zest/releaser/vcs.py", line 311, in _update_version
    raise RuntimeError("Cannot set version")
RuntimeError: Cannot set version
make: *** [Makefile:60: fullrelease] Error 1
```

My questions:

- is it possible to get an update with handling of the very convenient writing above ?
- is there any workaround ?

**Comment by reinout** [comment]
Does https://zestreleaser.readthedocs.io/en/latest/versions.html#using-the-version-number-in-setup-py-or-setup-cfg-as-version help?

**Comment by Aluriak** [comment]
Yes, it works ! Thank you for your quick reply !
