### ISSUE TITLE
zest.releaser with plone.releaser breaks when not in a buildout.coredev environment

### ISSUE THREAD

**Issue by thet** [zestsoftware/zest.releaser#384]
I have installed zest.releaser, plone.releaser and zest.releaser.towncrier in a central python virtualenv, which is available to my whole system.

When releasing a package which is not in Plone's buildout.coredev, zest.releaser gives me just before the end of the release process this error - note - up to uploading to pypi everything works fine:

```
Upload to pypi.quaive.net (Y/n)? n
Upload to quaivepypi.syslab.com (Y/n)? n
Ok to update coredev versions.cfg/checkouts.cfg? (Y/n)? n
Traceback (most recent call last):
  File "/home/thet/dev/python-tools/bin/fullrelease", line 8, in <module>
    sys.exit(main())
  File "/home/_thet/data/dev/python-tools/lib/python3.9/site-packages/zest/releaser/fullrelease.py", line 27, in main
    releaser.run()
  File "/home/_thet/data/dev/python-tools/lib/python3.9/site-packages/zest/releaser/baserelease.py", line 424, in run
    self._run_hooks('after')
  File "/home/_thet/data/dev/python-tools/lib/python3.9/site-packages/zest/releaser/baserelease.py", line 417, in _run_hooks
    utils.run_hooks(self.setup_cfg, which_releaser, when, self.data)
  File "/home/_thet/data/dev/python-tools/lib/python3.9/site-packages/zest/releaser/utils.py", line 685, in run_hooks
    run_entry_points(which_releaser, when, data)
  File "/home/_thet/data/dev/python-tools/lib/python3.9/site-packages/zest/releaser/utils.py", line 701, in run_entry_points
    plugin(data)
  File "/home/_thet/data/dev/python-tools/lib/python3.9/site-packages/plone/releaser/release.py", line 242, in update_other_core_branches
    CORE_BRANCHES.remove(current_core_branch)
ValueError: list.remove(x): x not in list
```

Maybe zest.releaser / plone.releaser should be more forgiving in a non-Plone coredev environment.

**Comment by mauritsvanrees** [comment]
That would be something to fix in `plone.releaser`. Please open an issue in https://github.com/plone/plone.releaser/issues

**Comment by mauritsvanrees** [comment]
BTW, I would not install `plone.releaser` anywhere else than in `buildout.coredev`.

**Comment by thet** [comment]
that probably fixes the issue. thanks!
